# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

### Create an array of 10 zeros 

In [2]:
a = np.zeros(10)

In [3]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
a = np.ones(10)

In [5]:
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
a = np.random.randint(5,6,10)

In [7]:
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [8]:
a = np.arange(10,51)

In [9]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [10]:
a = np.arange(10,51,2)

In [11]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
l = [[0,1,2],[3,4,5],[6,7,8]]
a = np.array(l)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [13]:
l = [[1,0,0],[0,1,0],[0,0,1]]
a = np.array(l)
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [14]:
a = np.random.randint(0,1)
a

0

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [15]:
a = np.random.randint(0,25,25)
a

array([ 0, 11,  8, 14,  9, 22, 14, 15, 11,  5, 14,  1, 13,  1,  8,  1,  7,
        1,  5,  0,  8,  0,  7, 12, 17])

#### Create the following matrix:

In [16]:
l = [[1,0,0,0,1],[1,1,0,0,1],[1,0,1,0,1],[1,0,0,1,1],[1,0,0,0,1]]
a = np.array(l)
a

array([[1, 0, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 0, 0, 1]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [17]:
a = np.linspace(0,1)
a

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [18]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [20]:
l = [[12,13,14,15],[17,18,19,20],[22,23,24,25]]
a = np.array(l)
a

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [21]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [22]:
a[1,3]

20

In [23]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [24]:
a = np.arange(1,26).reshape(5,5)
b = a[0:5,1]
c = b.reshape(5,1)
c

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [25]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [26]:
a = np.arange(21,26)
a

array([21, 22, 23, 24, 25])

In [27]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [28]:
a = np.arange(21,26).reshape(1,5)
b = np.arange(16,21).reshape(1,5)
c = np.concatenate((b,a))
c

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])